CREATE TABLE `le_foo` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`num` VARCHAR(1000) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1;


CREATE TABLE `le_bar` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`num` VARCHAR(1000) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1;
